comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

codecov:
  token: 7063be70-8437-4844-9258-e23dc9e96b16
